language: go

go:
  - 1.7

sudo: false

install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.12.2/glide-v0.12.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.12.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
